/** Code auto-generated by cOde 0.2 **/
#include <R.h> 
 #include <math.h> 

static double parms[37];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 500 
#define nSplines 0 
#define precision 1e-05 

#define k1 parms[0] 
 #define k2 parms[1] 
 #define k3 parms[2] 
 #define k4 parms[3] 
 #define y0_0 parms[4] 
 #define y1_0 parms[5] 
 #define y2_0 parms[6] 
 #define y3_0 parms[7] 
 #define y4_0 parms[8] 
 #define y5_0 parms[9] 
 #define y6_0 parms[10] 
 #define y7_0 parms[11] 
 #define y8_0 parms[12] 
 #define y9_0 parms[13] 
 #define y10_0 parms[14] 
 #define y11_0 parms[15] 
 #define y12_0 parms[16] 
 #define y13_0 parms[17] 
 #define y14_0 parms[18] 
 #define y15_0 parms[19] 
 #define y16_0 parms[20] 
 #define y17_0 parms[21] 
 #define y18_0 parms[22] 
 #define y19_0 parms[23] 
 #define y20_0 parms[24] 
 #define y21_0 parms[25] 
 #define y22_0 parms[26] 
 #define y23_0 parms[27] 
 #define y24_0 parms[28] 
 #define y25_0 parms[29] 
 #define y26_0 parms[30] 
 #define y27_0 parms[31] 
 #define y28_0 parms[32] 
 #define y29_0 parms[33] 
 #define y30_0 parms[34] 
 #define y31_0 parms[35] 
 #define y32_0 parms[36] 
#define tmin range[0]
#define tmax range[1]


void initmod(void (* odeparms)(int *, double *)) {
	 int N=37;
	 odeparms(&N, parms);
}

void initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -1*(k1*y[0]*y[1])+1*(k2*y[2])+1*(k3*y[2])-1*(k4*y[0]);
 	 ydot[1] = -1*(k1*y[0]*y[1])+1*(k2*y[2]);
 	 ydot[2] = 1*(k1*y[0]*y[1])-1*(k2*y[2])-1*(k3*y[2]);
 	 ydot[3] = 1*(k3*y[2]);
 	 ydot[4] = (-(k1*y[1]+k4))*(y[4])+(-(k1*y[0]))*(y[5])+(k2+k3)*(y[6]);
 	 ydot[5] = (-(k1*y[1]))*(y[4])+(-(k1*y[0]))*(y[5])+(k2)*(y[6]);
 	 ydot[6] = (k1*y[1])*(y[4])+(k1*y[0])*(y[5])+(-(k2+k3))*(y[6]);
 	 ydot[7] = (k3)*(y[6]);
 	 ydot[8] = (-(k1*y[1]+k4))*(y[8])+(-(k1*y[0]))*(y[9])+(k2+k3)*(y[10]);
 	 ydot[9] = (-(k1*y[1]))*(y[8])+(-(k1*y[0]))*(y[9])+(k2)*(y[10]);
 	 ydot[10] = (k1*y[1])*(y[8])+(k1*y[0])*(y[9])+(-(k2+k3))*(y[10]);
 	 ydot[11] = (k3)*(y[10]);
 	 ydot[12] = (-(k1*y[1]+k4))*(y[12])+(-(k1*y[0]))*(y[13])+(k2+k3)*(y[14]);
 	 ydot[13] = (-(k1*y[1]))*(y[12])+(-(k1*y[0]))*(y[13])+(k2)*(y[14]);
 	 ydot[14] = (k1*y[1])*(y[12])+(k1*y[0])*(y[13])+(-(k2+k3))*(y[14]);
 	 ydot[15] = (k3)*(y[14]);
 	 ydot[16] = (k3)*(0);
 	 ydot[17] = (-(k1*y[1]+k4))*(y[17])+(-(k1*y[0]))*(y[18])+(k2+k3)*(y[19])+-(y[0]*y[1]);
 	 ydot[18] = (-(k1*y[1]))*(y[17])+(-(k1*y[0]))*(y[18])+(k2)*(y[19])+-(y[0]*y[1]);
 	 ydot[19] = (k1*y[1])*(y[17])+(k1*y[0])*(y[18])+(-(k2+k3))*(y[19])+y[0]*y[1];
 	 ydot[20] = (k3)*(y[19]);
 	 ydot[21] = (-(k1*y[1]+k4))*(y[21])+(-(k1*y[0]))*(y[22])+(k2+k3)*(y[23])+y[2];
 	 ydot[22] = (-(k1*y[1]))*(y[21])+(-(k1*y[0]))*(y[22])+(k2)*(y[23])+y[2];
 	 ydot[23] = (k1*y[1])*(y[21])+(k1*y[0])*(y[22])+(-(k2+k3))*(y[23])+-y[2];
 	 ydot[24] = (k3)*(y[23]);
 	 ydot[25] = (-(k1*y[1]+k4))*(y[25])+(-(k1*y[0]))*(y[26])+(k2+k3)*(y[27])+y[2];
 	 ydot[26] = (-(k1*y[1]))*(y[25])+(-(k1*y[0]))*(y[26])+(k2)*(y[27]);
 	 ydot[27] = (k1*y[1])*(y[25])+(k1*y[0])*(y[26])+(-(k2+k3))*(y[27])+-y[2];
 	 ydot[28] = (k3)*(y[27])+y[2];
 	 ydot[29] = (-(k1*y[1]+k4))*(y[29])+(-(k1*y[0]))*(y[30])+(k2+k3)*(y[31])+-y[0];
 	 ydot[30] = (-(k1*y[1]))*(y[29])+(-(k1*y[0]))*(y[30])+(k2)*(y[31]);
 	 ydot[31] = (k1*y[1])*(y[29])+(k1*y[0])*(y[30])+(-(k2+k3))*(y[31]);
 	 ydot[32] = (k3)*(y[31]);

	 for(int i=  0 ; i <  3 ; ++i) RPAR[i] = 0;
}

