/** Code auto-generated by cOde 1.1.0 **/
#include <R.h> 
 #include <math.h> 

static double parms[50];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define kb1 parms[0] 
 #define kc1 parms[1] 
 #define kc2 parms[2] 
 #define kb2 parms[3] 
 #define kc4 parms[4] 
 #define k5 parms[5] 
 #define y0_0 parms[6] 
 #define y1_0 parms[7] 
 #define y2_0 parms[8] 
 #define y3_0 parms[9] 
 #define y4_0 parms[10] 
 #define y5_0 parms[11] 
 #define y6_0 parms[12] 
 #define y7_0 parms[13] 
 #define y8_0 parms[14] 
 #define y9_0 parms[15] 
 #define y10_0 parms[16] 
 #define y11_0 parms[17] 
 #define y12_0 parms[18] 
 #define y13_0 parms[19] 
 #define y14_0 parms[20] 
 #define y15_0 parms[21] 
 #define y16_0 parms[22] 
 #define y17_0 parms[23] 
 #define y18_0 parms[24] 
 #define y19_0 parms[25] 
 #define y20_0 parms[26] 
 #define y21_0 parms[27] 
 #define y22_0 parms[28] 
 #define y23_0 parms[29] 
 #define y24_0 parms[30] 
 #define y25_0 parms[31] 
 #define y26_0 parms[32] 
 #define y27_0 parms[33] 
 #define y28_0 parms[34] 
 #define y29_0 parms[35] 
 #define y30_0 parms[36] 
 #define y31_0 parms[37] 
 #define y32_0 parms[38] 
 #define y33_0 parms[39] 
 #define y34_0 parms[40] 
 #define y35_0 parms[41] 
 #define y36_0 parms[42] 
 #define y37_0 parms[43] 
 #define y38_0 parms[44] 
 #define y39_0 parms[45] 
 #define y40_0 parms[46] 
 #define y41_0 parms[47] 
 #define y42_0 parms[48] 
 #define y43_0 parms[49] 
#define tmin range[0]
#define tmax range[1]


void ccd4_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=50;
	 odeparms(&N, parms);
}

void ccd4_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void ccd4_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -1.0*(kb1*y[0]);
 	 ydot[1] = -1.0*(kc1*y[1])-1.0*(kc2*y[1]);
 	 ydot[2] = 1.0*(kb1*y[0])-1.0*(kb2*y[2])+1.0*(kc1*y[1]);
 	 ydot[3] = 1.0*(kb1*y[0])+1.0*(kb2*y[2])+1.0*(kc2*y[1]);
 	 ydot[4] = 1.0*(kc2*y[1])-1.0*(kc4*y[4])+1.0*(k5*y[6]);
 	 ydot[5] = 1.0*(kc1*y[1])+1.0*(kc4*y[4])+1.0*(k5*y[6]);
 	 ydot[6] = -1.0*(k5*y[6]);
 	 ydot[7] = (-kb1)*(y[7]);
 	 ydot[8] = (kb1)*(y[7])+(kc1)*(0.0)+(-kb2)*(y[8]);
 	 ydot[9] = (kb1)*(y[7])+(kc2)*(0.0)+(kb2)*(y[8]);
 	 ydot[10] = (-(kc1+kc2))*(y[10]);
 	 ydot[11] = (kb1)*(0.0)+(kc1)*(y[10])+(-kb2)*(y[11]);
 	 ydot[12] = (kb1)*(0.0)+(kc2)*(y[10])+(kb2)*(y[11]);
 	 ydot[13] = (kc2)*(y[10])+(-kc4)*(y[13])+(k5)*(0.0);
 	 ydot[14] = (kc1)*(y[10])+(kc4)*(y[13])+(k5)*(0.0);
 	 ydot[15] = (kb1)*(0.0)+(kc1)*(0.0)+(-kb2)*(y[15]);
 	 ydot[16] = (kb1)*(0.0)+(kc2)*(0.0)+(kb2)*(y[15]);
 	 ydot[17] = (kb1)*(0.0)+(kc2)*(0.0)+(kb2)*(0.0);
 	 ydot[18] = (kc2)*(0.0)+(-kc4)*(y[18])+(k5)*(0.0);
 	 ydot[19] = (kc1)*(0.0)+(kc4)*(y[18])+(k5)*(0.0);
 	 ydot[20] = (kc1)*(0.0)+(kc4)*(0.0)+(k5)*(0.0);
 	 ydot[21] = (kc2)*(0.0)+(-kc4)*(y[21])+(k5)*(y[23]);
 	 ydot[22] = (kc1)*(0.0)+(kc4)*(y[21])+(k5)*(y[23]);
 	 ydot[23] = (-k5)*(y[23]);
 	 ydot[24] = (-kb1)*(y[24])-y[0];
 	 ydot[25] = (kb1)*(y[24])+(kc1)*(0.0)+(-kb2)*(y[25])+y[0];
 	 ydot[26] = (kb1)*(y[24])+(kc2)*(0.0)+(kb2)*(y[25])+y[0];
 	 ydot[27] = (-(kc1+kc2))*(y[27])-y[1];
 	 ydot[28] = (kb1)*(0.0)+(kc1)*(y[27])+(-kb2)*(y[28])+y[1];
 	 ydot[29] = (kb1)*(0.0)+(kc2)*(y[27])+(kb2)*(y[28]);
 	 ydot[30] = (kc2)*(y[27])+(-kc4)*(y[30])+(k5)*(0.0);
 	 ydot[31] = (kc1)*(y[27])+(kc4)*(y[30])+(k5)*(0.0)+y[1];
 	 ydot[32] = (-(kc1+kc2))*(y[32])-y[1];
 	 ydot[33] = (kb1)*(0.0)+(kc1)*(y[32])+(-kb2)*(y[33]);
 	 ydot[34] = (kb1)*(0.0)+(kc2)*(y[32])+(kb2)*(y[33])+y[1];
 	 ydot[35] = (kc2)*(y[32])+(-kc4)*(y[35])+(k5)*(0.0)+y[1];
 	 ydot[36] = (kc1)*(y[32])+(kc4)*(y[35])+(k5)*(0.0);
 	 ydot[37] = (kb1)*(0.0)+(kc1)*(0.0)+(-kb2)*(y[37])-y[2];
 	 ydot[38] = (kb1)*(0.0)+(kc2)*(0.0)+(kb2)*(y[37])+y[2];
 	 ydot[39] = (kc2)*(0.0)+(-kc4)*(y[39])+(k5)*(0.0)-y[4];
 	 ydot[40] = (kc1)*(0.0)+(kc4)*(y[39])+(k5)*(0.0)+y[4];
 	 ydot[41] = (kc2)*(0.0)+(-kc4)*(y[41])+(k5)*(y[43])+y[6];
 	 ydot[42] = (kc1)*(0.0)+(kc4)*(y[41])+(k5)*(y[43])+y[6];
 	 ydot[43] = (-k5)*(y[43])-y[6];

	 for(int i=  0 ; i <  54 ; ++i) RPAR[i] = 0;
}

