/** Code auto-generated by cOde 0.2 **/
#include <R.h> 
 #include <math.h> 

static double parms[22];
static double forc[0];

#define alpha parms[0] 
 #define beta parms[1] 
 #define p1 parms[2] 
 #define p5 parms[3] 
 #define p2 parms[4] 
 #define p3 parms[5] 
 #define p4 parms[6] 
 #define sSTAT parms[7] 
 #define y0_0 parms[8] 
 #define y1_0 parms[9] 
 #define y2_0 parms[10] 
 #define y3_0 parms[11] 
 #define y4_0 parms[12] 
 #define y5_0 parms[13] 
 #define y6_0 parms[14] 
 #define y7_0 parms[15] 
 #define y8_0 parms[16] 
 #define y9_0 parms[17] 
 #define y10_0 parms[18] 
 #define y11_0 parms[19] 
 #define y12_0 parms[20] 
 #define y13_0 parms[21] 

void initmod(void (* odeparms)(int *, double *)) {
	 int N=22;
	 odeparms(&N, parms);
}

void initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = 1*2*alpha*time;
 	 ydot[1] = -1*beta*y[1];
 	 ydot[2] = -1*p1*y[0]*y[1]*y[2]+1*p5*y[10];
 	 ydot[3] = 1*p1*y[0]*y[1]*y[2]-2*p2*y[3]*y[3];
 	 ydot[4] = 1*p2*y[3]*y[3]-1*p3*y[4];
 	 ydot[5] = 1*p3*y[4]-1*p4*y[5];
 	 ydot[6] = 2*p4*y[5]-1*p5*y[6];
 	 ydot[7] = 1*p5*y[6]-1*p5*y[7];
 	 ydot[8] = 1*p5*y[7]-1*p5*y[8];
 	 ydot[9] = 1*p5*y[8]-1*p5*y[9];
 	 ydot[10] = 1*p5*y[9]-1*p5*y[10];
 	 ydot[11] = (1)*(-1*p1*y[0]*y[1]*y[2]+1*p5*y[10])+(1)*(1*p1*y[0]*y[1]*y[2]-2*p2*y[3]*y[3])+(2)*(1*p2*y[3]*y[3]-1*p3*y[4])+0+0;
 	 ydot[12] = 0+(sSTAT)*(1*p1*y[0]*y[1]*y[2]-2*p2*y[3]*y[3])+(sSTAT*2)*(1*p2*y[3]*y[3]-1*p3*y[4])+0+0;
 	 ydot[13] = 0+0+0+(y[1])*(1*2*alpha*time)+(y[0])*(-1*beta*y[1]);

}

