
## Class "datalist" and its constructor ------------------------------------------


#' Split a data.frame into a datalist
#' 
#' @param dataframe data.frame 
#' @param split.by character vector. A unique identifier is generated by \link{interaction}
#' of the columns corresponding to \code{split.by}.
#' @return Object of class \link{datalist}
#' @export
#' @examples 
#' mydata <- data.frame(name = "A", time = 0, value = c(0, 1), sigma = .1, condition = 1:2)
#' as.datalist(mydata)
as.datalist <- function(dataframe, split.by = "condition") {
  UseMethod("as.datalist", dataframe)
}
#' @export
as.datalist.data.frame <- function(dataframe, split.by = "condition") {
  
  remaining.names <- setdiff(names(dataframe), split.by)
  
  conditions <- lapply(split.by, function(n) dataframe[, n])
  splits <- do.call(interaction, c(conditions, list(sep = "_")))
  
  dataframe <- cbind(splits, dataframe[, remaining.names])
  
  out <- lapply(unique(splits), function(s) subset(dataframe, dataframe[, 1] == s)[, -1])
  names(out) <- as.character(unique(splits))
  
  datalist(out)
  
}

## Methods for class datalist ---------------------------------------

#' @export
print.datalist <- function(datalist) {
  for(n in names(datalist)) {
    cat(n, ":\n", sep = "")
    print(datalist[[n]])
  }
}



#' Plot a list data points
#' 
#' @param data Named list of data.frames as being used in \link{res}, i.e. with columns \code{name}, \code{time}, 
#' \code{value} and \code{sigma}.
#' @param ... Further arguments going to \code{subset}. 
#' @param scales The scales argument of \code{facet_wrap} or \code{facet_grid}, i.e. \code{"free"}, \code{"fixed"}, 
#' \code{"free_x"} or \code{"free_y"}
#' @param facet Either \code{"wrap"} or \code{"grid"}
#' @details The data.frame being plotted has columns \code{time}, \code{value}, \code{sigma},
#' \code{name} and \code{condition}.
#'  
#' 
#' @return A plot object of class \code{ggplot}.
#' @export
plot.datalist <- function (data, ..., scales = "free", facet = "wrap") {
  
  data <- subset(lbind(data), ...)
  
  if(facet == "wrap")
    p <-  ggplot(data, aes(x = time, y = value, ymin = value - sigma, 
                           ymax = value + sigma, group = condition, color = condition)) + facet_wrap(~name, scales = scales)
  if(facet == "grid")
    p <- ggplot(data, aes(x = time, y = value, ymin = value - sigma, 
                          ymax = value + sigma)) +  facet_grid(name~condition, scales = scales)
  
  p <- p + geom_point() + geom_errorbar(width = 0)
  
  
  attr(p, "data") <- data
  return(p)
  
}
